# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

chicago_crimes:
  target: dev
  outputs:
    dev:
      dbname: CHICAGO_CRIMES
      host: host.docker.internal
      password: SpartansWin$2022
      port: 5432
      schema: public
      type: postgres
      user: postgres